#!/bin/bash

# Detecting a logged in user
if [ -n "$SUDO_USER" ]; then
    USER="$SUDO_USER"
else
    USER="$(whoami)"
fi
echo "Logged in user: $USER"

vEnvPath="/opt/snatch/venv/"

echo "Запуск rabbitmq и memcached..."
rabbitmq-server -detached
systemctl start memcached

echo "Создание виртуальной среды Python"
mkdir -p $vEnvPath
chmod 755 $vEnvPath

if [ -d env ]; then
	rm -rf env
	echo "Удаление существующей виртуальной среды Python"
fi

echo "Активация виртуальной среды Python"
cd $vEnvPath
python3 -m venv env
. env/bin/activate

# Install the pip packages that are absent in the apt repo
pip3 install PIPDEPENDENCIESPLACEHOLDER --upgrade

pythonVersion=$(/opt/snatch/venv/env/bin/python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
ln -s "/usr/lib/python3/dist-packages/vmi/" "/opt/snatch/venv/env/lib/python$pythonVersion/site-packages/"

# Separate vmi (v4.0)
#pip3 install /usr/bin/snatch/vmi --upgrade
#rm -rf /usr/bin/snatch/vmi

deactivate 
cd - > /dev/null

touch /var/log/snatch.log
chmod 755 /var/log/snatch.log
chown $USER:$USER /var/log/snatch.log

if [ -d Snatch/migrations ]; then
	rm -rf Snatch/migrations
fi

mkdir -p /home/$USER/snatch/media/
chmod 755 /home/$USER/snatch/media/
chown $USER:$USER /home/$USER/snatch/media/

DB_NAME="snatch_db"
DB_USER="snatch_user"
DB_PASSWORD=$(tr -dc A-Za-z0-9 < /dev/urandom | head -c 16)

systemctl enable postgresql

# Check if PostgreSQL is running
if ! systemctl is-active --quiet postgresql; then
  echo "PostgreSQL is not running. Starting..."
  systemctl start postgresql
fi

# Drop the existing database if it exists
if sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
  echo "Database $DB_NAME already exists. Dropping and recreating..."

  # Terminate all connections to the database
  sudo -u postgres psql -c "SELECT pg_terminate_backend(pg_stat_activity.pid) 
    FROM pg_stat_activity 
    WHERE pg_stat_activity.datname = '$DB_NAME' AND pid <> pg_backend_pid();"

  sudo -u postgres psql -c "DROP DATABASE $DB_NAME;"
fi

# Create a new database
echo "Creating database $DB_NAME..."
sudo -u postgres psql -c "CREATE DATABASE $DB_NAME;"

# Create user if it does not exist
echo "Creating user $DB_USER..."
if sudo -u postgres psql -t -c "\du" | cut -d \| -f 1 | grep -qw $DB_USER; then
  echo "User $DB_USER already exists, going to recreate it."
  sudo -u postgres psql -c "DROP USER $DB_USER;"
fi

sudo -u postgres psql -c "CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';"

# Grant privileges to the user on the database
sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;"
sudo -u postgres psql -c "ALTER DATABASE $DB_NAME OWNER TO $DB_USER;"

sed -i "s/default_password/$DB_PASSWORD/g" /usr/bin/snatch/snatch/settings.py

# Reactivate virtual environment
cd - > /dev/null
source env/bin/activate

/usr/bin/snatch/manage.py makemigrations Snatch
/usr/bin/snatch/manage.py migrate

# Some created subdirs have the root permissions any way, so we will fix it once again for all subdirs
chmod -R 755 $vEnvPath

running=""
attempt=1

sudo -u $USER /usr/bin/snatch/snatch_start.sh
# echo "Ожидаем запуск SNatch..."

# while [[ -z $running ]]
# do
# 	running=$(grep "ready." /var/log/snatch.log)
# 	sleep 1
# 	echo "... "$attempt"s."
# 	attempt=$((attempt+1))
# done
# echo "SNatch запущен."


echo -e "\n\e[0;33mУчётные данные для прямого доступа к БД PostgreSQL:\e[0m"
echo "==========================================="
echo -e "\e[0;33m Имя БД: $DB_NAME\e[0m"
echo -e "\e[0;33m Пользователь: $DB_USER\e[0m"
echo -e "\e[0;33m Пароль: $DB_PASSWORD\e[0m"
echo "==========================================="

# Creating user for CI support
/usr/bin/snatch/manage.py createsuperuser --username ci_bot --email ci@bot.com --noinput
echo -e "Внимание! Этот токен может быть использован для CI API запросов (он также сохранён в /usr/bin/snatch/ci_token.txt)."
/usr/bin/snatch/manage.py drf_create_token ci_bot | awk '{print $3}' | tee /usr/bin/snatch/ci_token.txt

echo -e "\e[1;32mSNatch VERSIONPLACEHOLDER был установлен.\e[0m"

availSpace4calc=$(df -m /home/$USER/snatch/media/ --output=avail | tail -n1 | xargs)
availSpace=$(bc <<< "scale=1; $availSpace4calc/1024")

if [[ $availSpace4calc -lt 40960 ]]; then
	echo "Только "$availSpace"Гб места доступно в /home/$USER/snatch/media/, где SNatch хранит распакованные данные проектов для анализа. Этого достаточно только для очень коротких сценариев, однако для объемных сценариев могут потребоваться сотни гигабайт свободного места. Вы можете изменить заданный по умолчанию каталог с помощью скрипта /usr/bin/snatch/changedatadir.sh"
elif [[ $availSpace4calc -lt 102400 ]]; then
	echo $availSpace"Гб доступно в /home/$USER/snatch/media/, где SNatch хранит распакованные данные проектов для анализа. Этого достаточно для обычных сценариев, однако для объемных сценариев могут потребоваться сотни гигабайт свободного места. Вы можете изменить заданный по умолчанию каталог с помощью скрипта /usr/bin/snatch/changedatadir.sh"
else
	echo "Свободное место: в порядке"
fi

echo -e "\033[32mTo use ИСП РАН SNatch open \e[0m\e[1;32mhttp://localhost:8000\e[0m\033[32m in your browser.\e[0m"

echo -e "\033[32mДокументация доступна по ссылке: https://github.com/ispras/natch/blob/release/docs/9_snatch.md.\e[0m"