#!/bin/sh

case "$1" in
    purge)

        logFile="/var/log/snatch.log"
        settingsFile="/usr/bin/snatch/snatch/settings.py"

        # If the data dir was changed it's stored in a file
        if [ -f "/var/opt/snatch/datadir" ]; then
            mediaDir=$(cat "/var/opt/snatch/datadir")
        # Else this should be a default dir
        else
            mediaDir=$(find /home/*/snatch -mindepth 1 -maxdepth 1 -type d -not -empty 2>/dev/null)
        fi

        if [ -f "$logFile" ]; then
            # Interactive mode
            if [ -t 0 ] && [ -t 1 ]; then
                read -p "Удалить файл лога ($logFile)? [Y/n] " response
                case "$response" in
                    [nN][oO]|[nN])
                        echo "Файл лога сохранён."
                        ;;
                    *)
                        rm -f "$logFile"
                        echo "Файл лога удалён."
                        ;;
                esac

            # Non-interactive mode: removing
            else
                rm -f "$logFile"
                echo "Файл лога удалён"
            fi
        fi

        if [ ! -z $mediaDir ] && [ ! -z "$(ls -A $mediaDir)" ]; then
            # Interactive mode
            if [ -t 0 ] && [ -t 1 ]; then
                read -p "Удалить каталог с проектами ($mediaDir)? [Y/n] " response
                case "$response" in
                    [nN][oO]|[nN])
                        echo "Каталог с проектами сохранён."
                        ;;
                    *)
                        rm -rf "$mediaDir"
                        echo "Каталог с проектами удалён."
                        ;;
                esac

            # Non-interactive mode: removing
            else
                rm -rf "$mediaDir"
                echo "Каталог с проектами удалён."
            fi
            rm -rf "/var/opt/snatch/"
        fi

        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Other cases
        ;;
esac

rm -rf "/opt/snatch/venv/" "/usr/bin/snatch/"
echo "SNatch удалён."

exit 0