#!/bin/sh

case "$1" in
    purge)

        logFile="/var/log/snatch.log"
        settingsFile="/usr/bin/snatch/snatch/settings.py"

        mediaDir=$(grep "^MEDIA_ROOT = " "$settingsFile" | cut -d'=' -f2)
        if [[ $mediaDir == *"os.path"* ]]; then
            mediaDir=$(/usr/bin/python3 -c "import os; print($mediaDir)")
        else
            mediaDir=$(echo $mediaDir | sed "s/'//g")
        fi

        if [ -f "$logFile" ]; then
            # Interactive mode
            if [ -t 0 ] && [ -t 1 ]; then
                echo "Удалить файл лога ($logFile)? [Y/n]"
                read -r response
                case "$response" in
                    [nN][oO]|[nN])
                        echo "Файл лога сохранён."
                        ;;
                    *)
                        rm -f "$logFile"
                        echo "Файл лога удален."
                        ;;
                esac

            # Non-interactive mode: removing
            else
                rm -f "$logFile"
                echo "Файл лога удален"
            fi
        fi

        if [ ! -z "$(ls -A $mediaDir)" ]; then
            # Interactive mode
            if [ -t 0 ] && [ -t 1 ]; then
                echo "Удалить каталог с проектами ($mediaDir)? [Y/n]"
                read -r response
                case "$response" in
                    [nN][oO]|[nN])
                        echo "Каталог с проектами сохранён."
                        ;;
                    *)
                        rm -rf "$mediaDir"
                        echo "Каталог с проектами удалён."
                        ;;
                esac

            # Non-interactive mode: removing
            else
                rm -rf "$mediaDir"
                echo "Каталог с проектами удалён."
            fi
            rm -rf "/opt/snatch/venv/" "/usr/bin/snatch/"
        fi

        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Other cases
        rm -rf "/opt/snatch/venv/" "/usr/bin/snatch/"
        ;;
esac

echo "SNatch удален."

exit 0