#!/bin/bash

set -e

# Detecting a logged in user
if [ -n "$SUDO_USER" ]; then
    USER="$SUDO_USER"
else
    USER="$(whoami)"
fi
echo "Останавливаем SNatch..."

sudo -u $USER /usr/bin/snatch/snatch_stop.sh